### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by SaschaPeukert** [szenyo/neo4jscraperproc#1]
Hej, 

Nice work you got here! Would you mind adding a license to your code? I am sure other people (myself very much included) would like to take this thing a bit further :-)

If you need help picking one, I suggest going to https://choosealicense.com/

Cheers, and thank you!

**Comment by szenyo** [comment]
Hi,
thanks for your comment. It is on my list, I will do it next week. 👍
