### ISSUE TITLE
Can't get my Neo4j instance to work

### ISSUE THREAD

**Issue by casaar97** [szenyo/neo4jscraperproc#2]
Hi! I am really interested in using this tool, its amazing!

I am using **Neo4j community edition 3.5.3** version. 

I have downloaded the jar file, added it into the plugins folder and added the next sentence to my neo4j.conf file: **dbms.security.procedures.unrestricted=scraper.***

However, once I go to the terminal and run ./neo4j start in order to turn on the database into localhost:7474 port it doesn't start running.
 
I have the next issue in my log file:

2020-04-18 11:44:38.236+0000 INFO  ======== Neo4j 3.5.3 ========
2020-04-18 11:44:38.245+0000 INFO  Starting...
2020-04-18 11:44:42.390+0000 ERROR Failed to start Neo4j: Starting Neo4j failed: 

Component 'org.neo4j.server.database.LifecycleManagingDatabase@4b808427' was successfully initialized, but failed to start. 

Please see the attached cause exception "class org.jsoup.nodes.LeafNode overrides final method childNodeSize.()I".

**Comment by szenyo** [comment]
Hi @casaar97 !

Is this the only plugin in your plugin directory?

**Comment by casaar97** [comment]
It wasn't, I removed the other one that I had and now the database runs perfectly.

However, when I try to use scrape neo4j customers as you do in your YouTube video (https://www.youtube.com/watch?v=qU3xMBRiy78) it says: 

**Neo.ClientError.Procedure.ProcedureNotFound: There is no procedure with the name `scraper.select` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.**

And it doesn't appear among my procedures when I list them. I can't get to the point of why it isn't working:

This is my config:

**Neo4j database folder:**

<img width="571" alt="image" src="https://user-images.githubusercontent.com/22341152/79685256-aa49d900-8237-11ea-8807-2c5f3028ddb9.png">


**Neo4j plugins folder:**

<img width="813" alt="image" src="https://user-images.githubusercontent.com/22341152/79684957-89808400-8235-11ea-81ff-05f1023201f4.png">

**neo4j.conf:**

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/22341152/79685002-bd5ba980-8235-11ea-8355-1c9535813f9c.png">

**Neo4j web browser query and error message:**

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/22341152/79685037-f5fb8300-8235-11ea-8c18-dcd185d11e95.png">

Do you know what can be causing that?

Thanks for your quick response :)

**Comment by szenyo** [comment]
If you do not see them when you do
`call dbms.procedures`

then my wild guess is that you have multiple dbms.security.procedures.unrestricted keys in your config file.
It is possible that you have:
dbms.security.procedures.unrestricted=apoc.*
dbms.security.procedures.unrestricted=scraper.*

The proper usage is like this:
dbms.security.procedures.unrestricted=scraper.*,apoc.*

**Comment by casaar97** [comment]
It was what you said, I had the **dbms.security.procedures.unrestricted=apoc.*** sentence in the config file. 

Once I removed it everything worked perfectly.

Thank you so much for your help! Your scraper is very cool. :D
